
import './globals.css'
import Header from './components/Header'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className='min-h-screen bg-slate-900 scroll'
      >
          <Header />
          {children}
        </body>
    </html>
  )
}
